In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype="i4")
print(arr.dtype)

int32


In [6]:
arr.astype('int8')

array([1, 2, 3, 4], dtype=int8)

In [14]:
arr = np.array([1, 2, 3, 4])
view_arr = arr.view()
view_arr.shape = (2, 2)  # works, arr stays 1D
print(arr.shape)
print(view_arr.shape)
print(view_arr)
print(arr)
barr=arr
print(view_arr.base)
print(barr.base)

(4,)
(2, 2)
[[1 2]
 [3 4]]
[1 2 3 4]
[1 2 3 4]
None


In [20]:
arr = np.array([[[2,3,4,5], [3,4,56,4], [2,34,55,5]]])
arr.flatten()
print(arr.flatten())
print((arr.flatten()).ndim)
arr2 = arr.reshape(-1)
print(arr2.ndim)
print(arr2)

[ 2  3  4  5  3  4 56  4  2 34 55  5]
1
1
[ 2  3  4  5  3  4 56  4  2 34 55  5]


In [27]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Initial 2D array (3x3)
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Initial 3D array (2x3x3)
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d)
transposed_3d = arr_3d.T
print(transposed_3d)
print(arr_3d.transpose(1,0,2))


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[[[ 1 10]
  [ 4 13]
  [ 7 16]]

 [[ 2 11]
  [ 5 14]
  [ 8 17]]

 [[ 3 12]
  [ 6 15]
  [ 9 18]]]
[[[ 1  2  3]
  [10 11 12]]

 [[ 4  5  6]
  [13 14 15]]

 [[ 7  8  9]
  [16 17 18]]]


In [30]:
arr = np.arange(9).reshape(3, 3).T  # transpose = non-contiguous memory
raveled = arr.ravel()
flatter=arr.reshape(-1)
print(flatter,raveled)
print(raveled.base)  # False → it’s a copy!
print(flatter.base)


[0 3 6 1 4 7 2 5 8] [0 3 6 1 4 7 2 5 8]
None
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat = arr.reshape(-1)

print(flat)  # [1 2 3 4 5 6]
print(flat.base is arr) #t
flat[0] = 999
print(arr)  # 😨 might or might not change!

arr = np.arange(9).reshape(3, 3)
print(flat)
sliced = arr[:,:]  # take columns 0 & 2
flattened = sliced.reshape(-1)  

print(flattened.base is sliced)  #f
print(sliced.base is arr) #t
print(flattened.base is arr) #t


arr = np.array([[1, 2, 3], [4, 5, 6]])
flat = arr.ravel()
print(flat.base is arr)#t


flat[0] = 999
print(flat.base is arr)#t


arr = np.arange(9).reshape(3, 3)
print(flat.base is arr)#f
sliced = arr[:, ::2]  # columns 0 & 2
flat = sliced.ravel()

print(flat.base is sliced) # f
print(sliced.base is arr) #t

[1 2 3 4 5 6]
True
[[999   2   3]
 [  4   5   6]]
[999   2   3   4   5   6]
False
False
False
True
True
False
False
False


In [33]:
arr1 = np.ones((2, 1, 4))  # shape (2,1,4)
arr2 = np.ones((3, 4))  # shape (3,4)

print((arr1 * arr2))


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [37]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.stack((arr1, arr2), axis=1)  # Concatenate along axis 1 (columns)
print(arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
c = np.array([[100, 200, 300], [400, 500, 600], [700, 800, 900]])
d = np.array([['a','b','c'],['d','e' ,'f'],['g','h','i']])
result = np.stack((a, b, c), axis=2) 
result1 = np.add((a, b, c, d), axis=1) 
print(result1)
print(result1.shape)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> None