In [21]:
import numpy as np
k=3
data=np.loadtxt('spice_locations.txt',delimiter=",")
print(data)
print(data[np.random.choice(data.shape[0],k,replace=False)])
        

[[-2.12729941e+00  1.75357153e+00]
 [-3.40030291e-01 -6.70757901e-03]
 [-3.21990680e+00 -2.22002740e+00]
 [-3.70958194e+00  1.33088073e+00]
 [-9.94424941e-01  5.40362889e-01]
 [-3.89707753e+00  1.84954926e+00]
 [ 1.62213204e-01 -1.93830445e+00]
 [-3.09087516e+00 -2.08297745e+00]
 [-2.47878879e+00 -3.76217842e-01]
 [-1.84027491e+00 -1.54385430e+00]
 [-9.40735526e-01 -2.30253070e+00]
 [-2.53927676e+00 -1.16819078e+00]
 [-1.71965008e+00  9.25879807e-01]
 [-3.00163109e+00 -4.28827808e-01]
 [-1.03792716e+00 -2.76774794e+00]
 [-9.62275740e-01 -2.14737938e+00]
 [-3.67474204e+00  1.74442769e+00]
 [ 8.28160165e-01  1.04198674e+00]
 [-2.47693115e+00 -2.51163943e+00]
 [-5.78834867e-01 -7.99237531e-01]
 [-3.38980883e+00 -5.24115449e-01]
 [-3.82805739e+00  1.54660201e+00]
 [-2.70610009e+00  3.12611422e-01]
 [-2.44144462e+00 -3.99659894e-01]
 [-1.26644860e+00 -2.07572772e+00]
 [ 8.47923139e-01  8.75664117e-01]
 [ 6.97494708e-01  1.47413675e+00]
 [-1.01050011e+00  1.60937118e+00]
 [-3.55753749e+00 -2

In [17]:
np.ones(data.shape[0],dtype=int)
centers=data[np.random.choice(data.shape[0],k,replace=False)]

In [19]:
print(np.shape(data[:,None,:]))
print(np.shape(centers[None,:,:]))
print((np.linalg.norm(data[:, None, :] - centers[None, :, :], axis=2)))

(60, 1, 2)
(1, 3, 2)
[[ 4.07120353  6.16181074  2.15859852]
 [ 2.22927458  6.67357737  2.17044367]
 [ 2.25879962  9.97535138  1.98718132]
 [ 4.43237913  7.61264469  2.10452781]
 [ 2.68793454  6.46227944  1.74455045]
 [ 4.95867927  7.44474326  2.63923893]
 [ 1.14376034  8.36181477  3.06838819]
 [ 2.12957346  9.79042584  1.81319555]
 [ 2.33170003  8.03136319  0.        ]
 [ 1.06542248  8.69879315  1.33081737]
 [ 0.15663943  9.03244231  2.46501299]
 [ 1.85627113  8.72252577  0.79427951]
 [ 3.16520741  6.53122454  1.50723252]
 [ 2.6669064   8.38550612  0.52548252]
 [ 0.62496422  9.5030212   2.79204198]
 [ 0.          8.89439259  2.33170003]
 [ 4.74379971  7.32826223  2.43463378]
 [ 3.65755615  5.30909358  3.59822395]
 [ 1.5578403   9.85164667  2.1354224 ]
 [ 1.40161098  7.49826615  1.94647644]
 [ 2.9202573   8.70295293  0.92294703]
 [ 4.67527572  7.57034054  2.34899169]
 [ 3.01537363  7.62243368  0.72536624]
 [ 2.28964276  8.02907013  0.04409214]
 [ 0.31249815  8.93934709  2.0876069 ]
 [ 3