In [1]:
import numpy as np
from time import time
import matplotlib.pyplot as plt

# **What is a numpy array**?

What makes it different from a list?
### 1. Generally single datatype allowed.

In [3]:
def fun():
  return 0
l = ["This is a String", 3, -3.0, fun]

for ele in l:
  print(ele, type(ele))

print("-"*100)

nparr = np.array([1, 2, 3])
print(nparr.dtype)
nparr = np.array([1.0, 2, 3])
print(nparr.dtype)

print("-"*100)

# Heterogenous data is allowed but is not so useful
nparr = np.array([1.0, 2, 3], dtype = object)
print(nparr)
print(np.array(l).dtype)

This is a String <class 'str'>
3 <class 'int'>
-3.0 <class 'float'>
<function fun at 0x00000241D5BA44A0> <class 'function'>
----------------------------------------------------------------------------------------------------
int32
float64
----------------------------------------------------------------------------------------------------
[1.0 2 3]
object


### 2. Size of each dimension is fixed

In [3]:
l1 = [[1, 2, 3],
     [1, 2],
     [1]]
l2 = [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]

# nparr = np.array(l1)
nparr = np.array(l2)

print(nparr.shape)

# Because of this, each np array has a specific shape, which describes the length in each dimension
nparr = np.ones((2, 2, 5, 2))
print(nparr)
print(nparr.shape)

(3, 3)
[[[[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]
   [1. 1.]]]]
(2, 2, 5, 2)


Because of the above two constraints, NumPy arrays can be stored as a contiguous block in memory, unlike lists which store references to elements. 

Also the computations on NumPy arrays happen in C in the backend (Vectorized computations), thus allowing much faster and cleaner computations, while being very intuitive to manipulate and use.

# Element-wise Arithmetic and boolean operations

In [2]:
arr1 = np.random.randint(1, 10, (1000, 1000))
arr2 = np.random.randint(1, 10, (1000, 1000))

start = time()
# Code 1 (no for loops)
arr3 = arr1 + arr2
# Code 1 end
end = time()
print(f"Time of vectorized element wise addition: {end - start}")

start = time()
# Code 2
for i in range(arr1.shape[0]):
  for j in range(arr2.shape[1]):
    arr3[i][j] = arr1[i][j] + arr2[i][j]
# Code 2 end
end = time()
print(f"Time of non-vectorized element wise addition: {end - start}")


Time of vectorized element wise addition: 0.002385377883911133
Time of non-vectorized element wise addition: 0.6644034385681152


In [3]:
# We can do all kinds of element-wise operations
arr1 = np.random.randint(1, 10, (3, 3))
arr2 = np.random.randint(1, 10, (3, 3))

print(f"arr1 : \n{arr1}")
print("arr2 :")
print(arr2)

print("-"*10 + "Arithmetic" + "-"*10)
print(arr1 + arr2)
print(arr1 + 3)     # even constants work!
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 // arr2) # Integral division (floor)
print(arr1 % arr2)
print(arr1 ** arr2) # Even exponentiation!

arr1 : 
[[6 5 1]
 [2 3 3]
 [4 9 1]]
arr2 :
[[2 4 9]
 [3 4 5]
 [7 5 1]]
----------Arithmetic----------
[[ 8  9 10]
 [ 5  7  8]
 [11 14  2]]
[[ 9  8  4]
 [ 5  6  6]
 [ 7 12  4]]
[[12 20  9]
 [ 6 12 15]
 [28 45  1]]
[[3.         1.25       0.11111111]
 [0.66666667 0.75       0.6       ]
 [0.57142857 1.8        1.        ]]
[[3 1 0]
 [0 0 0]
 [0 1 1]]
[[0 1 1]
 [2 3 3]
 [4 4 0]]
[[   36   625     1]
 [    8    81   243]
 [16384 59049     1]]


In [4]:
print(f"arr1 : \n{arr1}")
print("arr2 :")
print(arr2)

print("-"*10 + "Boolean" + "-"*10)
print(arr1 > arr2)
print(arr1 < arr2)
print(arr1 >= arr2)
print(arr1 == arr2)
print(arr1 != arr2)

arr1 : 
[[6 5 1]
 [2 3 3]
 [4 9 1]]
arr2 :
[[2 4 9]
 [3 4 5]
 [7 5 1]]
----------Boolean----------
[[ True  True False]
 [False False False]
 [False  True False]]
[[False False  True]
 [ True  True  True]
 [ True False False]]
[[ True  True False]
 [False False False]
 [False  True  True]]
[[False False False]
 [False False False]
 [False False  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True False]]


# **Indexing**

In [ ]:
arr1[...] # What can you put inside these brackets??

# Ans: A LOT!
# We have already seen masking, where we put a boolean np array of the same size

### 1. Slicing

In [ ]:
# Different ways to slice in a single dimension
arr = np.arange(20)
print(arr[2:6])
print(arr[2:]) # Leave blank for the end
print(arr[:-8])# Leave blank for start
print(arr[0:8:2]) # [start : stop : step] (not including stop)

[2 3 4 5]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 2 4 6]



---
**Question**: What will ```arr[::2]``` do?

---

In [11]:
# Two ways of slicing for multi-dim arrays, they are very different, be careful.
print("arr1 :")
print(arr1)
print(arr1[1:3][0:1]) # sliced the first dimension twice!
print(arr1[1:2, 0:1]) # This is the "correct" way
# I was stuck for 2 days once, not realizing that I sliced wrong.

arr1 :
[[3 7 7]
 [5 4 1]
 [1 6 7]]
[[5 4 1]]
[[5]]


### 2. Boolean matrices as masks:

Let's suppose that we want to get all the elements in arr1 that are greater than 5:

In [ ]:
mask = arr1 > 5
print(arr1[mask])

[7 7 6 7]



---
**Question**: Given a NumPy array, ``arr``, print out all elements of `arr` that are strictly between **3** and **9**. 

**No for-loops!**

---

In [5]:
arr = np.random.randint(1, 5, 100)
n = np.log2(arr.size)
n = int(n)
indices = 2 ** np.arange(n)
arr[indices]

array([1, 3, 1, 2, 3, 2])

### 3. Array of indices

In [19]:
rows = [1, 0, 2]
cols = [2, 0, 1]
print("arr1 :")
print(arr1)
print(arr1[rows, cols])

arr1 :
[[3 7 7]
 [5 4 1]
 [1 6 7]]
[1 3 6]


# **Broadcasting**

Very powerful, very misunderstood

When you want to do any element wise operation (discussed above) on np arrays with different shapes.

Broadcasting has a rule (explained on the board), but it is advisable to use `np.newaxis` instead in the lab exam.

Suppose you want to get every pair wise sum of elements from a 1-dim array, `arr`

In [6]:
arr = np.random.randint(1, 5, 5)
print(arr)
print(arr.shape)                # (5,)
print(arr[:, np.newaxis].shape) # (5, 1) (very different from (5,))
print(arr[np.newaxis, :].shape) # (1, 5)

pair_wise_sum = arr[:, np.newaxis] + arr

print(pair_wise_sum)

[2 3 4 1 1]
(5,)
(5, 1)
(1, 5)
[[4 5 6 3 3]
 [5 6 7 4 4]
 [6 7 8 5 5]
 [3 4 5 2 2]
 [3 4 5 2 2]]



---
**Question:** Which of the following broadcasts work and which give error?
1. `[1, 2, 3] + [1, 2, 3, 4]`

2. `[[1, 2], [2, 3], [3, 4]] + [1, 2, 3] `

3. `[[[0], [1]], [[1], [2]]] > [[2], [-1]]`


In [6]:
# 1.
a = np.array([1, 2, 3])
b = np.array([1, 2, 3, 4])
try:
  print(a + b)
except:
  print("Nope")
# 2.
a = np.array([[1, 2], 
              [2, 3], 
              [3, 4]])
b = np.array([1, 2, 3])
try:
  print(a + b)
except:
  print("Nope")
# 3.
a = np.array([[[0], 
               [1]], 
              [[1], 
               [2]]])
b = np.array([[2], [-1]])
try:
  print(a > b)
except:
  print("Nope")


Nope
Nope
[[[False]
  [ True]]

 [[False]
  [ True]]]


---

# **Modification Operations**
We will see `np.stack` and `np.concatenate` (`np.hstack` and `np.vstack` as well)

In [27]:
a = np.array([[1, 2, 3],
              [5, 6, 7]])
b = np.array([2, 3, 4])

In [ ]:
# np.stack
# Creates new axis at 'axis', the input array must have the same shape!
print(a.shape)
print(b.shape)
bc = b[np.newaxis, :]
bc = b.reshape((1, 3))

bc = np.concatenate((b, b, b), axis = 0)
ac = np.array([a, b])

ac = np.vstack((a, b[np.newaxis, :])) # better practice
ac
print(np.stack((ac, bc), axis = 0).shape)
print(np.stack((ac, bc), axis = 1).shape)
print(np.stack((ac, bc), axis = 2).shape)

(2, 3)
(3,)
(2, 3, 3)
(3, 2, 3)
(3, 3, 2)


In [ ]:
# np.concatenate
# the axis at which you are concatenating can be different
# every other axis (dimension) should be of same size
print(ac.shape)
print(bc.shape)

ac = np.stack((a, a, a), axis = 1)
bc = np.stack((bc, bc), axis = 1)

(3, 3)
(3, 3)


In [ ]:
arr = np.random.randint(1, 10, 10)

M = 2*arr[:, np.newaxis] - arr[np.newaxis, :]
M = M**2

indices = np.arange(10)
X = indices[:, np.newaxis] - indices[np.newaxis, :]
np.sum(M[X < 0])

**Tip:** Keep `print(arr.shape)` handy!

In [26]:
# What are their shapes?
print(ac.shape)
print(bc.shape)
print(ac)
print(bc)
print(np.concatenate((ac, bc), axis = 1))

(3, 3)
(3, 3)
[[1 2 3]
 [2 3 4]
 [2 3 4]]
[[2 3 4]
 [2 3 4]
 [2 3 4]]
[[1 2 3 2 3 4]
 [2 3 4 2 3 4]
 [2 3 4 2 3 4]]


**Note**: `np.vstack` and `np.hstack` behaviour is similar to `np.concatenate`, not `np.stack`!

**Tip**: Try to only use `np.concatenate` and `np.stack`, you will only get confused with `np.vstack` and `np.hstack`
. You can't keep wondering in exam what it means to stack and which direction is horizontal and which is vertical.

In [ ]:
# np.hstack when you want to increase the size horizontally (second axis for every thing except 1-D arrays, Why?)
a = np.array([[1, 2, 3], 
              [2, 3, 4]])
b = np.array([[1], 
              [2]])

print(np.hstack((a, b)))


[[1 2 3 1]
 [2 3 4 2]]


In [ ]:
# np.vstack for the first dimension (axis) (expect for 1-D, where it reshapes it to (1, N))
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(np.vstack((a, b)))

a = np.vstack((a, b))
print(np.vstack((a, b)))

[[1 2 3]
 [2 3 4]]
[[1 2 3]
 [2 3 4]
 [2 3 4]]


# **Useful NP Functions**

---

Array Creation & Initialization

| Function                            | Description                                |
|-------------------------------------|--------------------------------------------|
| `np.array()`                        | Create an array from list/tuple            |
| `np.zeros((shape))`                 | All zeros                                  |
| `np.ones((shape))`                  | All ones                                   |
| `np.full((shape), val)`             | All elements set to `val`                  |
| `np.eye(n)`                         | Identity matrix                            |
| `np.arange(start, stop, step)`      | Like `range()`, evenly spaced values       |
| `np.linspace(start, stop, num)`     | `num` values between start and stop        |
| `np.random.rand(shape)`             | Uniform random values between 0 and 1      |
| `np.random.randn(shape)`            | Standard normal distribution               |
| `np.random.randint(low, high, size)`| Random integers                            |

---

Shape & Structure Manipulation

| Function                            | Description                                |
|-------------------------------------|--------------------------------------------|
| `a.reshape(new_shape)`              | Change shape without changing data         |
| `a.flatten()`                       | Flatten to 1D array                        |
| `np.transpose(a)` / `a.T`           | Transpose array                            |
| `np.expand_dims(a, axis)`           | Add a dimension                            |
| `np.squeeze(a)`                     | Remove dimensions of size 1                |
| `np.stack([a, b], axis=0)`          | Stack arrays along a new axis              |
| `np.hstack((a, b))`                 | Horizontal stack                           |
| `np.vstack((a, b))`                 | Vertical stack                             |
| `np.concatenate((a, b), axis=?)`    | Concatenate arrays                         |

---

Mathematical Operations

| Function                  | Description                              |
|---------------------------|------------------------------------------|
| `np.sum(a, axis=?)`       | Sum over an axis                         |
| `np.mean(a, axis=?)`      | Mean                                     |
| `np.median(a)`            | Median                                   |
| `np.std(a)`               | Standard deviation                       |
| `np.var(a)`               | Variance                                 |
| `np.min(a)` / `np.max(a)` | Min / Max                                |
| `np.argmin(a)` / `np.argmax(a)` | Indices of min / max            |
| `np.round(a, decimals)`   | Rounding                                 |

---

Linear Algebra  (`np.linalg`)

| Function                        | Description                              |
|---------------------------------|------------------------------------------|
| `np.linalg.norm(a)`             | Vector/matrix norm                       |
| `np.dot(a, b)`                  | Dot product                              |
| `np.matmul(a, b)`/ `a @ b`      | Matrix multiplication                    |
| `np.linalg.inv(a)`              | Matrix inverse                           |
| `np.linalg.det(a)`              | Determinant                              |

---

Logical & Comparison

| Function                  | Description                              |
|---------------------------|------------------------------------------|
| `np.all(a)` / `np.any(a)` | Check if all/any values are `True`       |
| `np.where(cond, x, y)`    | Element-wise `if cond: x else: y`        |
| `np.isclose(a, b)`        | Check element-wise approximate equality  |
| `np.equal(a, b)`          | Check element-wise equality              |

---


**Tip**: If you think (or don't think) that there might be a function for XYZ, there probably is.


---
**Question**: Given a input array `r` and `m` of positions and masses of point masses in the 2D plane `r.shape = (n, 2)` and `m.shape = (n,)`. Find the total Gravitational force (vector) on each of the masses (assume G = 1).

**No for-loops, otherwise you get a beating :)**

(*Hint : break it down into steps, what do you need first, the pair wise distance vector matrix (use something starting with Bro...), then this thing divided by the square of the distance (np.linalg.norm) (Take care of the diagonal entries). Then get the pair wise Force, then only one step remains, ... Figure it out on your own :).*)

---

Do you see why numpy (and python) is so powerful, imagine how much more code you have to write in C++.

# **Common mistakes**